--- cc-scripts installer / updater.
--
-- Self-contained by contract: this file may never require anything it installs,
-- because on a fresh computer it is the only file present.
--
-- Bootstrap:
--   wget run https://raw.githubusercontent.com/camadkins/cc-scripts/main/installer.lua
-- Afterwards:
--   update

local OWNER  = "camadkins"
local REPO   = "cc-scripts"
local BRANCH = "main"

local MANIFEST_REPO_PATH = "manifest.json"
local MANIFEST_LOCAL     = "/ccs/manifest.json"
local SHIM_PATH          = "/update.lua"

local unjson = textutils.unserialiseJSON or textutils.unserializeJSON

local cacheBustCounter = 0

local function colour(c, text)
  if term.isColour and term.isColour() then
    local prev = term.getTextColour()
    term.setTextColour(c)
    io.write(text)
    term.setTextColour(prev)
  else
    io.write(text)
  end
end

local function info(text) print(text) end
local function ok(text) colour(colours.lime, text) print("") end
local function warn(text) colour(colours.yellow, text) print("") end
local function fail(text) colour(colours.red, text) print("") end

--- Build the raw.githubusercontent URL for a repo path.
-- The cb= parameter defeats the ~5 minute GitHub CDN cache, which otherwise
-- serves the pre-push content to anyone updating immediately after a release.
local function rawUrl(repoPath)
  cacheBustCounter = cacheBustCounter + 1
  return ("https://raw.githubusercontent.com/%s/%s/%s/%s?cb=%d.%d")
    :format(OWNER, REPO, BRANCH, repoPath, os.epoch("utc"), cacheBustCounter)
end

--- Fetch one repo path. Returns content, or nil plus a message.
local function fetch(repoPath)
  local url = rawUrl(repoPath)
  local handle, err = http.get(url, { ["Cache-Control"] = "no-cache" })
  if not handle then
    return nil, ("%s: %s"):format(repoPath, tostring(err))
  end
  local body = handle.readAll()
  handle.close()
  if not body or #body == 0 then
    return nil, ("%s: empty response"):format(repoPath)
  end
  return body
end

local function readFile(path)
  if not fs.exists(path) then return nil end
  local handle = fs.open(path, "r")
  if not handle then return nil end
  local body = handle.readAll()
  handle.close()
  return body
end

local function writeFile(path, content)
  local dir = fs.getDir(path)
  if dir ~= "" and not fs.exists(dir) then fs.makeDir(dir) end
  local handle, err = fs.open(path, "w")
  if not handle then error(("cannot write %s: %s"):format(path, tostring(err))) end
  handle.write(content)
  handle.close()
end

--- Manifest entries are keyed by install path; index them for comparison.
local function indexByInstallPath(manifest)
  local byPath = {}
  if manifest and manifest.files then
    for _, entry in ipairs(manifest.files) do byPath[entry.path] = entry end
  end
  return byPath
end

local function loadInstalledManifest()
  local body = readFile(MANIFEST_LOCAL)
  if not body then return nil end
  local parsed = unjson(body)
  return parsed
end

--- Classify every install path as added / updated / unchanged / removed.
local function diffManifests(remote, installed)
  local remoteByPath    = indexByInstallPath(remote)
  local installedByPath = indexByInstallPath(installed)

  local added, updated, unchanged, removed = {}, {}, {}, {}

  for path, entry in pairs(remoteByPath) do
    local prev = installedByPath[path]
    if not prev then
      added[#added + 1] = entry
    elseif prev.sha1 ~= entry.sha1 then
      updated[#updated + 1] = entry
    else
      unchanged[#unchanged + 1] = entry
    end
  end

  for path in pairs(installedByPath) do
    if not remoteByPath[path] then removed[#removed + 1] = path end
  end

  table.sort(added,   function(a, b) return a.path < b.path end)
  table.sort(updated, function(a, b) return a.path < b.path end)
  table.sort(removed)

  return added, updated, unchanged, removed
end

local function writeShim()
  writeFile(SHIM_PATH, table.concat({
    "-- generated by cc-scripts installer; edits are overwritten on update",
    'local args = { ... }',
    'shell.run("/ccs/installer.lua", "update", table.unpack(args))',
  }, "\n") .. "\n")
end

--- Fetch every changed file into memory FIRST, then write.
-- Nothing on disk is touched until the whole set has been downloaded and
-- verified non-empty, so a mid-update HTTP failure leaves the previous
-- version fully intact rather than a mix of two releases.
local function apply(remote, added, updated, removed, dryRun)
  local work = {}
  for _, entry in ipairs(added)   do work[#work + 1] = entry end
  for _, entry in ipairs(updated) do work[#work + 1] = entry end

  if #work == 0 and #removed == 0 then
    ok("Already up to date (version " .. tostring(remote.version) .. ").")
    return true
  end

  for _, entry in ipairs(added)   do info("  + " .. entry.path) end
  for _, entry in ipairs(updated) do info("  ~ " .. entry.path) end
  for _, path  in ipairs(removed) do info("  - " .. path) end

  if dryRun then
    info(("%d to add, %d to update, %d to remove."):format(#added, #updated, #removed))
    return true
  end

  local staged = {}
  for _, entry in ipairs(work) do
    local body, err = fetch(entry.src)
    if not body then
      fail("Download failed, nothing written: " .. tostring(err))
      return false
    end
    staged[#staged + 1] = { path = entry.path, body = body }
  end

  for _, item in ipairs(staged) do writeFile(item.path, item.body) end
  for _, path in ipairs(removed) do
    if fs.exists(path) then fs.delete(path) end
  end

  writeFile(MANIFEST_LOCAL, textutils.serialiseJSON(remote))
  writeShim()

  ok(("Done. %d added, %d updated, %d removed -> version %s")
    :format(#added, #updated, #removed, tostring(remote.version)))
  return true
end

local function run(mode)
  info(("cc-scripts :: %s/%s@%s"):format(OWNER, REPO, BRANCH))

  local body, err = fetch(MANIFEST_REPO_PATH)
  if not body then
    fail("Cannot reach the manifest: " .. tostring(err))
    fail("Check that the computer has HTTP enabled and the branch exists.")
    return false
  end

  local remote = unjson(body)
  if type(remote) ~= "table" or type(remote.files) ~= "table" then
    fail("Manifest is malformed.")
    return false
  end

  local installed = loadInstalledManifest()
  if mode == "install" and installed then
    warn("Already installed; running as an update.")
  end

  local added, updated, unchanged, removed = diffManifests(remote, installed)

  if mode == "check" then
    info(("Remote version %s, %d files (%d unchanged)."):format(
      tostring(remote.version), #remote.files, #unchanged))
    return apply(remote, added, updated, removed, true)
  end

  return apply(remote, added, updated, removed, false)
end

local function uninstall(remote)
  local installed = loadInstalledManifest()
  if not installed then
    warn("Nothing installed.")
    return true
  end
  for _, entry in ipairs(installed.files) do
    if fs.exists(entry.path) then fs.delete(entry.path) end
  end
  if fs.exists(SHIM_PATH) then fs.delete(SHIM_PATH) end
  if fs.exists(MANIFEST_LOCAL) then fs.delete(MANIFEST_LOCAL) end
  ok("Uninstalled.")
  return true
end

local args = { ... }
local mode = args[1] or "install"

for index = 2, #args do
  local flag, value = args[index]:match("^%-%-(%w+)=(.+)$")
  if flag == "branch" then BRANCH = value
  elseif flag == "owner" then OWNER = value
  elseif flag == "repo" then REPO = value end
end

if mode == "install" or mode == "update" or mode == "check" then
  local success = run(mode)
  if not success then error("cc-scripts: " .. mode .. " failed", 0) end
elseif mode == "uninstall" then
  uninstall()
elseif mode == "version" then
  local installed = loadInstalledManifest()
  info(installed and tostring(installed.version) or "not installed")
else
  info("usage: installer.lua [install|update|check|uninstall|version] [--branch=NAME]")
end
