#!/usr/bin/env bun
/**
 * Copy the working tree into a live world's ComputerCraft directory, in exactly
 * the layout the installer produces. This is the local dev loop: edit in your
 * editor, run this, reboot the computer in game.
 *
 * Machine-specific paths live in .ccsync.json, which is untracked on purpose -
 * this repo is public and must never carry a home directory or a world name.
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildManifest, REPO_ROOT, serialise } from "./manifest-lib.ts";

interface SyncConfig {
  /** The .minecraft directory of the instance, e.g. <instances>/<name>/minecraft */
  instanceDir: string;
  world: string;
  computerId: number;
}

const CONFIG_PATH = join(REPO_ROOT, ".ccsync.json");

function die(message: string): never {
  console.error(message);
  process.exit(1);
}

function flag(name: string): string | undefined {
  const index = process.argv.indexOf(`--${name}`);
  return index === -1 ? undefined : process.argv[index + 1];
}

if (!existsSync(CONFIG_PATH)) {
  die(
    `Missing ${CONFIG_PATH}.\n` +
      `Copy .ccsync.example.json to .ccsync.json and point it at your instance.`,
  );
}

let config: SyncConfig;
try {
  config = JSON.parse(readFileSync(CONFIG_PATH, "utf8"));
} catch (error) {
  die(`.ccsync.json is not valid JSON: ${(error as Error).message}`);
}

const world = flag("world") ?? config.world;
const computerId = Number(flag("id") ?? config.computerId ?? 0);
const dryRun = process.argv.includes("--dry");

if (!config.instanceDir || !existsSync(config.instanceDir)) {
  die(`instanceDir does not exist: ${config.instanceDir}`);
}

const savesDir = join(config.instanceDir, "saves");
if (!existsSync(savesDir)) die(`No saves directory under ${config.instanceDir}`);

const worldDir = join(savesDir, world);
if (!existsSync(worldDir)) {
  const available = readdirSync(savesDir).join(", ") || "(none)";
  die(`World not found: ${world}\nAvailable worlds: ${available}`);
}

// CC:Tweaked creates the per-computer directory lazily, so seeding one before a
// computer is placed is normal. The world's computercraft directory existing at
// all is the real check: without it, this is the wrong world.
const rootDir = join(worldDir, "computercraft");
if (!existsSync(rootDir)) {
  die(`No computercraft directory in ${world}. Load the world with CC:Tweaked once, then re-run.`);
}
const ccDir = join(rootDir, "computer");

const target = join(ccDir, String(computerId));
const manifest = buildManifest();

console.log(`sync -> ${world} / computer ${computerId}`);

if (dryRun) {
  for (const file of manifest.files) console.log(`  would write ${file.path}`);
  console.log(`${manifest.files.length} file(s), dry run, nothing written`);
  process.exit(0);
}

mkdirSync(target, { recursive: true });

for (const file of manifest.files) {
  const destination = join(target, file.path);
  mkdirSync(join(destination, ".."), { recursive: true });
  copyFileSync(join(REPO_ROOT, file.src), destination);
  console.log(`  ${file.path}`);
}

// Mirror what the installer leaves behind, so a synced computer and an updated
// one are indistinguishable: the installed manifest and the `update` shim.
writeFileSync(join(target, "ccs", "manifest.json"), serialise(manifest));
writeFileSync(
  join(target, "update.lua"),
  [
    "-- generated by cc-scripts installer; edits are overwritten on update",
    "local args = { ... }",
    'shell.run("/ccs/installer.lua", "update", table.unpack(args))',
    "",
  ].join("\n"),
);
console.log(`  ccs/manifest.json`);
console.log(`  update.lua`);
console.log(`${manifest.files.length + 2} file(s) written. Reboot the computer in game.`);
